# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsAppxCode' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsAppxCode

  target 'NewsAppxCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsAppxCodeUITests' do
    # Pods for testing
  end

end
